# -*- coding: utf-8 -*-
"""UTS_compro2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16BuvzHgNtJcnqVQ1OPlape9O89NiEAcp
"""

# 1. DATA INPUT
raw_log = "ID:001#NAMA:kopi susu gula aren#QTY:3#PRICE:18000;ID:002#NAMA:COFFEE LATTE#QTY:1#PRICE:25000"

# 2. DATA SPLITTING (DOUBLE SPLIT)

# memisahkan dua transaksi berdasarkan ';'(split)
transaksi = raw_log.split(";")

# memecah setiap atribut transaksi berdasarkan'#' (split)
data1 = transaksi[0].split("#")
data2 = transaksi[1].split("#")

# 3. Pembersihan teks dan spasi (replace dan strip)

# transaksi 1
nama1 = data1[1].replace("NAMA:", "").strip()
qty1 = data1[2].replace("QTY:", "").strip()
price1 = data1[3].replace("PRICE:", "").strip()

# transaksi 2
nama2 = data2[1].replace("NAMA:", "").strip()
qty2 = data2[2].replace("QTY:", "").strip()
price2 = data2[3].replace("PRICE:", "").strip()

# mengubah nama menu menjadi tittle case
nama1 = nama1.title()
nama2 = nama2.title()

# mengubah string menjadi integrer
price1 = int(price1)
qty1 = int(qty1)
price2 = int(price2)
qty2 = int(qty2)

# 4. Perhitungan Aritmatika
subtotal1 = qty1 * price1
subtotal2 = qty2 * price2
total = subtotal1 + subtotal2

# 5. Output Laporan (F string dan Alignment)

print("=" * 60)
print(f"{'LAPORAN HARIAN KEDAI SOU SPACE':^60}")
print("=" * 60)
print(f"{'MENU':<30}{'QTY':<6}{'HARGA':<10}{'SUBTOTAL'}")
print("-" * 60)
print(f"{nama1:<30}{qty1:<6}{price1:<10}{subtotal1}")
print(f"{nama2:<30}{qty2:<6}{price2:<10}{subtotal2}")
print("-" * 60)
print(f"{'TOTAL PENDAPATAN HARI INI:':<36}Rp {total}")
print("=" * 60)